spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gobang?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    session:
      timeout: 30m

jwt:
  secret: gobang-jwt-secret-key-2024-dev-environment
  expiration: 86400000

security:
  ignored:
    urls:
      - "/user/login"
      - "/user/register"
      - "/user/info"
      - "/api/user/login"
      - "/api/user/register"
      - "/test/**"
      - "/ws/**"
      - "/findMatch"
      - "/game"

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
